# Simple workflow for deploying Jupyter Book to GitHub Pages
name: Deploy Jupyter Book to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Jupyter Book
        run: |
          pip install -U jupyter-book

      - name: Build Jupyter Book
        run: |
          jupyter-book build .

      - name: Upload built book as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Optional: Publish book metadata to remote index (if needed)
      # Uncomment and configure this step if you need to use dzsquared/jupyter-publish-action
      # - name: Remote Jupyter Book Publish
      #   uses: dzsquared/jupyter-publish-action@v0.1.0
      #   with:
      #     directory: ./_build/html
      #     releasename: 1
      #     bookname: Kalman Filtering
      #     versionnumber: 1
      #     languageid: EN
      #     githubtoken: ${{ secrets.GITHUB_TOKEN }}
